const {
  ReactIcon,
  ReduxIcon,
  TypescriptIcon,
  HTMLIcon,
  // JSIcon,
  // FirebaseIcon,
  // GraphQLIcon,
  // CSS3Icon,
  // VueIcon,
  // VuexIcon,
  // SocketIOIcon,
  // NodeJSIcon,
  // MongoDBIcon,
  // LaravelIcon,
  // PhpIcon,
  // RedisIcon,
  // JWTIcon,
  // PostgresIcon,
  // MySQLIcon,
  // GitIcon,
  // GithubIcon,
  // NPMIcon,
  // YarnIcon,
} = require("@/icons/TechnologiesIcons").default;

export default [
  {
    id: 1,
    icon: [ReactIcon, ReactIcon, ReactIcon],
    thumbnail: "/images/project-image-1.png",
    title: "Some title",
    description: "Some description",
  },
  {
    id: 2,
    icon: ReduxIcon,
    thumbnail: "/images/project-image-1.png",
    title: "Some title",
    description: "Some description",
  },
  {
    id: 3,
    icon: HTMLIcon,
    thumbnail: "/images/project-image-1.png",
    title: "Some title",
    description: "Some description",
  },
  {
    id: 4,
    icon: TypescriptIcon,
    thumbnail: "/images/project-image-1.png",
    title: "Some title",
    description: "Some description",
  },
];
